# SPDX-FileCopyrightText: 2023 The libsensible Authors
#
# SPDX-License-Identifier: Unlicense

name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - os/ci

defaults:
  run:
    working-directory: ./

env:
  CFLAGS: -O1 -g 

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: webiny/action-conventional-commits@v1.1.0
    - uses: actions/checkout@v2
    # - run: ./scripts/checks/headers-have-pragmas.sh
    # - run: ./scripts/licences.sh check
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
  Tests:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: awalsh128/cache-apt-pkgs-action@latest
    #   with:
    #     packages:
    #     version: 1.0
    - run: ./scripts/ci.sh
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: (success() || failure()) && github.event_name == 'pull_request' # always run even if the previous step fails
      with:
        report_paths: 'libsensible-*/test-results.xml'
