# SPDX-FileCopyrightText: 2023 The libsensible Authors
#
# SPDX-License-Identifier: Unlicense

name: Tests

on:
  pull_request:
  push:

defaults:
  run:
    working-directory: ./

env:
  CFLAGS: -O1 -g 

jobs:

  Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: webiny/action-conventional-commits@v1.1.0
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2

  Tests:
    permissions:
      contents: read
      checks: write
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - if: runner.os == 'Windows'
      name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - run: cmake -DCMAKE_BUILD_TYPE=Debug -B debug
    - run: cmake --build debug -t check
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: (success() || failure()) && github.event_name == 'pull_request' # always run even if the previous step fails
      with:
        report_paths: 'debug/test/test-results.xml'

  Tests-windows:
    permissions:
      contents: read
      checks: write
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - run: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -B debug
    - run: cmake --build debug -t check
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: (success() || failure()) && github.event_name == 'pull_request' # always run even if the previous step fails
      with:
        report_paths: 'debug/test/test-results.xml'
